### ISSUE TITLE
Filter out "indoor" PurpleAir stations

### ISSUE THREAD

**Issue by deanlyoung** [airq-dev/airq#42]
They can be misleading when they are lower than the outdoor readings, and also bring down averages.

**Comment by ianhoffman** [comment]
Hi Dean, we actually already do this on the build side. I should put something about this in the README, but basically, we run a cron job once per week (Sunday nights) on an EC2 box which builds a sqlite3 database of sensors, zipcodes, and the distances between them, and uploads it to this repository. That code is [here](https://github.com/airq-dev/airq-data). We then use that database to do geolocation (using geohashing and the haversine formula).

During the build process, we filter out bad sensors: https://github.com/airq-dev/airq-data/blob/master/src/build.py#L247-L271

But you're right that we should bring this logic into the application too, as new Purpleair sensors can come online and existing sensors can suffer fluctuations during the course of a week (between builds).

The current application-side filtering we do lives [here](https://github.com/airq-dev/airq/blob/master/app/airq/purpleair.py#L42), if you want to take a look.

**Comment by deanlyoung** [comment]
Ah, I see that now. Nice. I mainly mentioned it because I was mistakenly using a nearby indoor station for a personal project. It was significantly higher than my indoor levels (although I filter my air), so I was none the wiser. 🤦🏻‍♂️

**Comment by ianhoffman** [comment]
Yeah, you definitely have to do a good amount of data cleaning when using Purpleair. But it's cool that they provide (seemingly) unfiltered (ha) access to the sensor data, and let us shoot ourselves in our own feet with it.
