### ISSUE TITLE
Switch to Purpleair's Experimental JSON API

### ISSUE THREAD

**Issue by ianhoffman** [airq-dev/airq#44]
I think switching to Purpleair's experimental JSON API, in which sensors are encoded as lists instead of maps, would offer a slight speed increase for uncached requests because the amount of data we'd need to receive over the wire would be substantially less. For details on the experimental JSON API, see [this document](https://docs.google.com/document/d/15ijz94dXJ-YAZLi9iZ_RaBwrZ4KtYeCy08goGBwnbCU/edit?usp=sharing) under the `JSON data available from PurpleAir` section.

**Comment by deanlyoung** [comment]
One issue I ran into with the experimental API is that it seems to more aggressively rate limit, but that could be anecdotal.

**Comment by ianhoffman** [comment]
Ah, that's interesting. IIRC (@wdanfort can confirm) they said they'd like us to make no more than one request per sensor per 10 minute interval, and to batch requests, which we try to do.

**Comment by deanlyoung** [comment]
Fetching all data once every 10 minutes sounds like a good compromise (if they allow that). Loading all stations definitely takes a few seconds, but that shouldn't matter when fetching occurs every 10 minutes anyway.

There is a plug-in for Homebridge that defaults to every 90 seconds and hasn't shown any problems, but that is for a single station at a time.

Additionally, I've tested against a single station and received a 429 error code asking me to try again somewhere between 25~30 seconds. fwiw

**Comment by ianhoffman** [comment]
Yeah, that's an idea I've been kicking around a bit for the past couple days. Maybe you can help me think through it.

Exactly as you suggest, I was thinking of pulling down all the data from Purpleair every ten minutes. The problem is that, currently, we run two application servers behind a load balancer. This is obviously a somewhat overly-engineered architecture for what we're doing at the moment, but I like having some redundancy and I also was familiar with how to get this architecture stood up. Each application server is a stateless container running in ECS Fargate. So if the application servers make their own requests, we'd need to make two requests every ten minutes. If one makes requests every 5, 15, 25... minutes, and one makes requests every 0, 10, 20... minutes, we should be fine. But, that's a hacky thing to hardcode into the application servers and I'd rather not do it that way.

The better way is probably to set up another container which runs Celery, or just use our existing EC2 box, to make a request every 10 minutes. The question then becomes: how do we get this data to the application servers? Well, for now we could just insert it all into Memcached. Ideally we would instead insert it into Postgres and start aggregating time-series data.

The reason I've been hesitant to make this change is twofod:
1) It's a bit of work to set up Celery / a task runner. I'm not sure how high the payoff is given that, today, once the cache is warm responses are quite fast, and once we have a decent amount of users the cache should always be warm. Hell, a stopgap solution would be to set-up a Raspberry Pi to make a query for sensors around SF every 10 minutes, thus warming the cache.
2) I hate paying high AWS bills and I don't know what the data transfer cost will be to insert a bunch of data into Memcached/Postgres every ten minutes. ElastiCache is already the bulk of our AWS bill, and it's actually way more expensive than I thought it would be: something like $5/day just at current levels of activity. So if we, say, quadruple that amount of data we're inserting, I'd be out a couple hundred dollars a month. This is just an open-source project 😄 . (That said, I think I'm using a larger Memcached node than I need to be using. I'll see what the cost-savings are if I scale that down.)
  Maybe Postgres, which we run on the free tier, could better handle that sort of load, cost-wise?

I don't know if you have any insight here. I'm sort of new to running my own infra on AWS — done one other hobby project but that's it.

**Comment by deanlyoung** [comment]
It mostly depends on what the roadmap is. I saw some ToDo items in the ReadME, but it's not clear whether the focus is to start tracking data overtime (using historical trends... for something), aggregation (adding other sources), the delivery mechanism (SMS, Slack, etc.), or maybe something else...

What is/are the solutions this is providing?
- help me quickly find the nearest outdoor station...
- tell me whether it's good/bad right now...
- trending up/down...
- there is better air in X/Y/Z...
- etc...

**Comment by ianhoffman** [comment]
I think the solutions we're currently aiming for are:
* tell me whether it's good/bad right now...
* there is better air in X/Y/Z...

If we had historical data, we could expand into:
* trending up/down...
* notify me when air quality fluctuates by a significant amount

That would be an interesting direction to go in. We already have users' phone numbers and the zipcodes in which they're interested, so we could easily give them updates when air quality fluctuates by X.

Aside from that, I think the focus is relatively open. I'm just interested in building an open-source project and seeing if people find it useful and/or enjoy contributing to it. So I view this as half a learning opportunity for myself.

Aggregation is complicated. I'm not sure how we'd do it, but it's also a really interesting direction. For example, if we have Airnow and Purpleair data, how do we combine them to provide a superior estimate? I don't know.

**Comment by ianhoffman** [comment]
> Fetching all data once every 10 minutes sounds like a good compromise (if they allow that). Loading all stations definitely takes a few seconds, but that shouldn't matter when fetching occurs every 10 minutes anyway.
> 
> There is a plug-in for Homebridge that defaults to every 90 seconds and hasn't shown any problems, but that is for a single station at a time.
> 
> Additionally, I've tested against a single station and received a 429 error code asking me to try again somewhere between 25~30 seconds. fwiw

This is done now. Next steps will be to start creating some historical record of this data.
